### ISSUE TITLE
Slight optimisation in the mesh creation script

### ISSUE THREAD

**Issue by Gorgious56** [paireks/dotbim-blender#2]
Hello !

I noticed ~15% faster mesh instantiation by using list comprehensions instead of `while` loops in verts and faces creation on a mesh with ~280k triangles. Not noticeable for small meshes but it can add up on heavy files.

I replaced https://github.com/paireks/dotbim-blender/blob/757ce21c9ee3ab21c68ae844ba699560a84f38b8/script.py#L6-L19

with

    vertices = [
        (dotbim_mesh.coordinates[counter], 
        dotbim_mesh.coordinates[counter + 1], 
        dotbim_mesh.coordinates[counter + 2]) 
        for counter in range(0, len(dotbim_mesh.coordinates), 3)
    ]
    faces = [
        (dotbim_mesh.indices[counter], 
        dotbim_mesh.indices[counter + 1], 
        dotbim_mesh.indices[counter + 2]) 
        for counter in range(0, len(dotbim_mesh.indices), 3)
    ]

Feel free to take into consideration or discard if not interested. 

Thanks for the project. 

Cheers :)

**Comment by paireks** [comment]
Hi, it's great :), would you mind creating PR, so I will merge it?

**Comment by Gorgious56** [comment]
Sure thing ! https://github.com/paireks/dotbim-blender/pull/3

**Comment by paireks** [comment]
Thank you @Gorgious56! If you'd like to try to develop exporter part as well - just let me know!
