### ISSUE TITLE
Scaling

### ISSUE THREAD

**Issue by paireks** [paireks/dotbim-blender#5]
When scaling is attached to element, then export doesn't take it into an account.

**Comment by paireks** [comment]
![2022-05-02_18h11_14](https://user-images.githubusercontent.com/47977819/166268136-662bd8da-47f4-4e01-9e1d-bf902d095b94.png)
[Scale.zip](https://github.com/paireks/dotbim-blender/files/8604225/Scale.zip)

@Gorgious56 do you have an idea how to get this scale and take it into account? Do we need to make a transformation by ourselves or there is a smarter way? Currently we manually "normalize" the scale to 1.0.

**Comment by Gorgious56** [comment]
Sure it can be applied dynamically at export time by fetching the evaluated object. I'll issue a fix !

**Comment by Gorgious56** [comment]
It just has one limitation, if two objects that share the same mesh in blender have been scaled differently, they will come out as referencing different meshes on export. So it won't be possible to roundtrip the data in this way

**Comment by paireks** [comment]
Great! For me works right now, thank you :)
